Chapter 2
kennedy-ak/MLOps pull request #2
Opened 2024-11-12 13:02 UTC by kennedy-ak

Implementation of MLflow for tracking and managing the ML lifecycle for taxi trip duration prediction. The steps includes data preprocessing, model training with autologging, hyperparameter tuning, and promoting the best model to the MLflow registry based on test RMSE. All tasks complete, with the best model registered for future deployment.

2024-11-12 13:03 UTC, kennedy-ak commented
added reviewer

2024-11-14 09:37 UTC, Silas-Asamoah requested changes
There's a bunch of binary files you need to gitignore

2024-11-14 11:45 UTC, kennedy-ak commented
gitignored binary files (mlruns) from the mlflow-experinment directory

2024-11-29 05:44 UTC, Silas-Asamoah commented
@kennedy-ak you still have conflicts in this pull request, kindly resolve them

2025-01-20 09:39 UTC, Silas-Asamoah requested changes
Everything looks good I left a few comments for you to check out but there are merge conflicts that need to be resolved before merging to the base branch

2025-01-20 09:39 UTC, Silas-Asamoah commented on .gitignore
> +/002-experinment-tracking/002-training/experinment-Tracking/mlflow.db
You don't need to include every single file or directory in your gitignore. e.g You've already generally ignore .db files so including /002-experinment-tracking/002-training/experinment-Tracking/mlflow.db in the gitignore is redundant

2025-01-27 21:27 UTC, merged